# Kafka 개발환경용 Docker Compose
# Alert 시스템 개발 및 테스트를 위한 Kafka 클러스터

version: '3.8'

services:
  # Zookeeper 서비스
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: ssom-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - ssom-network
    restart: unless-stopped

  # Kafka 브로커
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: ssom-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      # 브로커 설정
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      
      # 리스너 설정
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      
      # 토픽 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      
      # 성능 및 로그 설정
      KAFKA_LOG_RETENTION_HOURS: 168          # 7일
      KAFKA_LOG_RETENTION_BYTES: 1073741824   # 1GB
      KAFKA_LOG_SEGMENT_BYTES: 67108864       # 64MB
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_COMPRESSION_TYPE: lz4
      
      # JMX 모니터링
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: localhost
      
      # JVM 힙 설정
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
      
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - ssom-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kafdrop (Kafka UI)
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    hostname: kafdrop
    container_name: ssom-kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: "-Xms64M -Xmx128M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    networks:
      - ssom-network
    restart: unless-stopped

  # Schema Registry (선택사항)
  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    hostname: schema-registry
    container_name: ssom-schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - ssom-network
    restart: unless-stopped

# 네트워크 정의
networks:
  ssom-network:
    name: ssom-network
    driver: bridge

# 볼륨 정의  
volumes:
  zookeeper-data:
    name: ssom-zookeeper-data
  zookeeper-logs:
    name: ssom-zookeeper-logs
  kafka-data:
    name: ssom-kafka-data
